kind: pipeline
name: mon-super-pipeline-ci
    
steps:
  - name: hello-world
    image: busybox
    commands:
      - echo 'Hello World'
  
  - name: testing
    image: lowess/preact-cli
    commands: 
       - npx preact-cli create ${DRONE_REPO}#${DRONE_COMMIT} test
       - cd test
       - npm install
       - npm run build

  - name: slack
    image: plugins/slack
    settings: 
      webhook: 
        from_secret : slack_webhook
      channel: drone-ci
      username: Fabien Hamelle
      template: >
        {{#success build.status}}
          Build {{build.number}} réussi. Wakanda forever !
        {{else}}
          Build {{build.number}} échoué. Oups...
        {{/success}}
        Lien : https://{{ repo.owner }}.github.io/{{ repo.name }}/
